# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warface_checker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"/* Общий темный фон софта и дефолтный аккуратный шрифт */\n"
"QMainWindow {\n"
"    background-color: #1e1e24;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    font-size: 13px;\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit, QSpinBox, QPlainTextEdit {\n"
"    background-color: #2a2a32;\n"
"    border: 1px solid #3f3f48;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"}\n"
"QLineEdit:focus, QSpinBox:focus {\n"
"    border: 1px solid #114e7d;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #3f3f48;\n"
"    border-radius: 6px;\n"
"    margin-top: 12px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2a2a32;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3f3f48;\n"
"    border-radius: 4px;\n"
"    padding: 6px 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #35353f;\n"
"    border: 1px solid #114e7d;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #202026;\n"
"}\n"
"\n"
"/* Главная кнопка Запуска */\n"
"QPushButton#btn_start {\n"
"    background-color: #114e7d;\n"
"    color: #ffffff;\n"
"    font-size: 13px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 12px;\n"
"}\n"
"QPushButton#btn_start:hover {\n"
"    background-color: #165b8f;\n"
"}\n"
"QPushButton#btn_start:pressed {\n"
"    background-color: #0b3759;\n"
"}\n"
"QPushButton#btn_start:disabled {\n"
"    background-color: #555555;\n"
"    color: #aaaaaa;\n"
"}\n"
"\n"
"QTabWidget::pane { \n"
"    border: 1px solid #3f3f48; \n"
"    background-color: #1e1e24;\n"
"}\n"
"QTabBar::tab {\n"
"    background: #2a2a32;\n"
"    padding: 8px 20px;\n"
"    color: #b0b0b0;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    border: 1px solid #3f3f48;\n"
"    border-bottom: none;\n"
"    margin-right: 2px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #1e1e24;\n"
"    color: #ffffff;\n"
"    border-bottom: 2px solid #114e7d;\n"
"}\n"
"\n"
"/* СТИЛИЗАЦИЯ ТАБЛИЦЫ РЕЗУЛЬТАТОВ */\n"
"QTableWidget {\n"
"    background-color: #202026;\n"
"    gridline-color: #2e2e38;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3f3f48;\n"
"    border-radius: 4px;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"}\n"
"QTableWidget::item:hover {\n"
"    background-color: #35353f;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #114e7d;\n"
"    color: #ffffff;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #2a2a32;\n"
"    color: #b0b0b0;\n"
"    padding: 6px;\n"
"    border: 1px solid #2e2e38;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #b0b0b0;\n"
"}\n"
"QCheckBox {\n"
"    color: #e0e0e0;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: #2a2a32;\n"
"    border: 1px solid #3f3f48;\n"
"    border-radius: 3px;\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #114e7d;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #114e7d;\n"
"    border: 1px solid #165b8f;\n"
"}\n"
"\n"
"/* Строгий стиль для виджета статистики */\n"
"QWidget#stats_widget {\n"
"    background-color: #1e1e24;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Обычный аккуратный шрифт для параметров без жирности */\n"
"QLabel#lbl_good, QLabel#lbl_bad, QLabel#lbl_threads, QLabel#lbl_proxies_count {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 4px;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"QLabel#lbl_good {\n"
"    color: #2ecc71;\n"
"}\n"
"QLabel#lbl_bad {\n"
"    color: #e74c3c;\n"
"}\n"
"QLabel#lbl_threads {\n"
"    color: #b0b0b0;\n"
"}\n"
"QLabel#lbl_proxies_count {\n"
"    color: #b0b0b0;\n"
"}\n"
"\n"
"/* Мелкий шрифт 11px специально для счетчика оставшихся аккаунтов */\n"
"QLabel#lbl_remaining {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 4px;\n"
"    font-size: 11px;\n"
"    color: #8a8a93;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.edit_accounts = QtWidgets.QLineEdit(self.groupBox)
        self.edit_accounts.setObjectName("edit_accounts")
        self.gridLayout.addWidget(self.edit_accounts, 0, 1, 1, 1)
        self.btn_browse_accounts = QtWidgets.QPushButton(self.groupBox)
        self.btn_browse_accounts.setObjectName("btn_browse_accounts")
        self.gridLayout.addWidget(self.btn_browse_accounts, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.edit_proxies = QtWidgets.QLineEdit(self.groupBox)
        self.edit_proxies.setObjectName("edit_proxies")
        self.gridLayout.addWidget(self.edit_proxies, 1, 1, 1, 1)
        self.btn_browse_proxies = QtWidgets.QPushButton(self.groupBox)
        self.btn_browse_proxies.setObjectName("btn_browse_proxies")
        self.gridLayout.addWidget(self.btn_browse_proxies, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spin_threads = QtWidgets.QSpinBox(self.groupBox)
        self.spin_threads.setMinimum(1)
        self.spin_threads.setMaximum(100)
        self.spin_threads.setProperty("value", 3)
        self.spin_threads.setObjectName("spin_threads")
        self.gridLayout.addWidget(self.spin_threads, 2, 1, 1, 2)
        self.label_delay = QtWidgets.QLabel(self.groupBox)
        self.label_delay.setObjectName("label_delay")
        self.gridLayout.addWidget(self.label_delay, 3, 0, 1, 1)
        self.spin_delay = QtWidgets.QSpinBox(self.groupBox)
        self.spin_delay.setMinimum(0)
        self.spin_delay.setMaximum(3600)
        self.spin_delay.setProperty("value", 5)
        self.spin_delay.setObjectName("spin_delay")
        self.gridLayout.addWidget(self.spin_delay, 3, 1, 1, 2)
        self.check_verify_proxy = QtWidgets.QCheckBox(self.groupBox)
        self.check_verify_proxy.setObjectName("check_verify_proxy")
        self.gridLayout.addWidget(self.check_verify_proxy, 4, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)
        self.stats_widget = QtWidgets.QWidget(self.centralwidget)
        self.stats_widget.setObjectName("stats_widget")
        self.horizontalLayout_stats = QtWidgets.QHBoxLayout(self.stats_widget)
        self.horizontalLayout_stats.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_stats.setObjectName("horizontalLayout_stats")
        self.lbl_good = QtWidgets.QLabel(self.stats_widget)
        self.lbl_good.setObjectName("lbl_good")
        self.horizontalLayout_stats.addWidget(self.lbl_good)
        self.lbl_bad = QtWidgets.QLabel(self.stats_widget)
        self.lbl_bad.setObjectName("lbl_bad")
        self.horizontalLayout_stats.addWidget(self.lbl_bad)
        self.lbl_remaining = QtWidgets.QLabel(self.stats_widget)
        self.lbl_remaining.setObjectName("lbl_remaining")
        self.horizontalLayout_stats.addWidget(self.lbl_remaining)
        self.lbl_threads = QtWidgets.QLabel(self.stats_widget)
        self.lbl_threads.setObjectName("lbl_threads")
        self.horizontalLayout_stats.addWidget(self.lbl_threads)
        self.lbl_proxies_count = QtWidgets.QLabel(self.stats_widget)
        self.lbl_proxies_count.setObjectName("lbl_proxies_count")
        self.horizontalLayout_stats.addWidget(self.lbl_proxies_count)
        self.verticalLayout.addWidget(self.stats_widget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_log)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_log = QtWidgets.QPlainTextEdit(self.tab_log)
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName("txt_log")
        self.verticalLayout_2.addWidget(self.txt_log)
        self.tabWidget.addTab(self.tab_log, "")
        self.tab_results = QtWidgets.QWidget()
        self.tab_results.setObjectName("tab_results")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_results)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_results = QtWidgets.QTableWidget(self.tab_results)
        self.table_results.setObjectName("table_results")
        self.table_results.setColumnCount(4)
        self.table_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.table_results)
        self.btn_save = QtWidgets.QPushButton(self.tab_results)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_3.addWidget(self.btn_save)
        self.tabWidget.addTab(self.tab_results, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Warface Multi-Account Checker"))
        self.groupBox.setTitle(_translate("MainWindow", "Настройки чекера"))
        self.label.setText(_translate("MainWindow", "Файл аккаунтов:"))
        self.edit_accounts.setPlaceholderText(_translate("MainWindow", "Выберите файл с базами (email:pass)..."))
        self.btn_browse_accounts.setText(_translate("MainWindow", "Обзор..."))
        self.label_2.setText(_translate("MainWindow", "Файл прокси:"))
        self.edit_proxies.setPlaceholderText(_translate("MainWindow", "Выберите файл с прокси (необязательно)..."))
        self.btn_browse_proxies.setText(_translate("MainWindow", "Обзор..."))
        self.label_3.setText(_translate("MainWindow", "Потоки:"))
        self.label_delay.setText(_translate("MainWindow", "Задержка (сек):"))
        self.check_verify_proxy.setText(_translate("MainWindow", "Проверять прокси перед стартом"))
        self.btn_start.setText(_translate("MainWindow", "Запустить потоки чекера"))
        self.lbl_good.setText(_translate("MainWindow", "Good: 0"))
        self.lbl_bad.setText(_translate("MainWindow", "Bad: 0"))
        self.lbl_remaining.setText(_translate("MainWindow", "Осталось: 0"))
        self.lbl_threads.setText(_translate("MainWindow", "Потоки: 0"))
        self.lbl_proxies_count.setText(_translate("MainWindow", "Количество Прокси: 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), _translate("MainWindow", " Лог работы "))
        item = self.table_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Email"))
        item = self.table_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Proxy"))
        item = self.table_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_results.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Donat"))
        self.btn_save.setText(_translate("MainWindow", "Сохранить результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_results), _translate("MainWindow", " Результаты "))
